@page { 
    size: 8.27in 11.69in; /* A4 width and height */ 
	margin-top: 0.10in;            
          
}
.pageClass { 
	font-size: 8pt; 
	font-family: Arial Unicode MS;

}
.defibHr{
	border-top: 1px solid #000000;
}
.defibtable{
	margin-top: 3pt;
}
table.defibTable td{
	vertical-align: top;
}
.defibH3{
	font-size: 12pt;
	margin-bottom: 0.5pt;
	margin-top: 1pt;
	font-weight: lighter;
}
.defibH4{
	font-size: 11pt;
	margin-bottom: 1pt;
	margin-top: 3pt;
}
.defibP{
	margin: 0.5px;	
}
.border, .border tr, .border td{
	margin-top: 3pt;
	border: 0.5px solid black;
	border-collapse: collapse;
	border-spacing: 0px;
	text-align: center;
	padding: 1.5px;
	min-height: 8pt;
	}
.border th{
	background-color: #D3D3D3;
	text-align: center;
	border-top: 0px solid black;
}
.topcorner{
	top:0;
	right:0;
	text-align: right;
	padding-right:20pt;
}
.defibHeader{
	font-size: 12pt;
	position:absolute;
}
.noteboxs{
	border: 1px solid black;
	width: 480pt;
	height: 45pt;
	float: right;
	margin-top: 10px;
}