 @page {
    margin:0in;
}

.mdrf_container {
	margin-right: 0.32in;   
    font-family:Arial Unicode MS;
    font-size:11px;
}

.mdrf_table {
    width:100%; 
}
table.mdrf_table td.shrink {
    white-space:nowrap;padding:0 4px 0 0;
}
table.mdrf_table td.expand { 
    border-bottom:0.5px solid black;
    width:29%;padding:0 4px 0 0;
}
table.mdrf_table td.rotationTD {
    position:relative;
    margin:0 0 0 -75px;
}
.mdrf_headingText {
    font-family:Helvetica;
    font-size:14px;
    font-weight:bold;
}
.inlineTable {
    margin-left: 0.10in;    
}
.mdrf_heading {
    text-align: center;
}
.mdrf_deviceTable {
    border: 3px solid black;
}

.mdrf_manufactureTable td{
    border: 0.1px solid #A9A9A9;
    width:100%;
}
.mdfr_hr {
    height: 2px;
    color:#A9A9A9;
    background-color:#A9A9A9;
    border: 0;
    margin-left: 0.32in;
}        