@page {
	margin : 0cm 0cm 0cm 0cm;	
}

.page-break {
    display : block;
    page-break-before:always;
}

.oss_container {
    padding : 1cm 1cm 0cm 1cm;
    font-family: sans-serif;
}           
.oss_patientinfo {
    border-width : 1px;
    border-collapse : collapse;
    width : 100%;
    margin-top : 4px;
    font-size  : 10px;
    margin-left : 2px;
}

table.oss_patientinfo td {
    border : 1px solid black;
    border-collapse : collapse;
    min-height : 29px;
    width : 75%;
    vertical-align : text-top;
    padding-left : 4px;
    padding-top : 4px;  
}

.oos_deviceinfo_header {
    width : 100%;
    font-size : 13px;
    margin-top : 5px;
    margin-bottom : 5px;
}

table.oos_deviceinfo_header td {
    padding-left : 5px;
    vertical-align : middle;
}

.oos_deviceinfo_table {
    border-width : 1px;
    width : 100%;
    border-collapse : collapse;
    font-size : 10px;
}

table.oos_deviceinfo_table td {
    border : 1px solid black;
    min-height : 29px;
    width : 25%;
    vertical-align : text-top;
    padding-left : 4px;
    padding-top : 4px;         
}

.oos_patientexpired_table {
    width:100%;
    border-collapse : collapse;
    margin-top : 3px;
}

table.oos_patientexpired_table td {
    border : 1px solid black;
    vertical-align : text-top;
    padding-left : 5px;
}

.oos_footer_table {
    margin-top : 7px;
    padding-left : 5px;             
    border-collapse : collapse;
    width : 100%;   
}

table.oos_footer_table td {
    border : 1px solid black;
    min-height : 29px;
    vertical-align : text-top;
    font-size : 10px;
    padding-left : 5px;
}

.oos_checkbox_div {
    width : 10px;
    height : 10px;
    border : 1px solid black;
    display : inline-block;
}

.oos_deviceexperience_table {
    margin-top : 7px;
    padding-left : 5px;             
    border-collapse : collapse;
    margin-bottom:5px;
    width : 100%;
    font-size:10px;
}

table.oos_deviceexperience_table td {
    border : 1px solid black;        
}

.oos_device_cell {
    display:table-cell;
    width:5%;
    padding:4px 4px 4px 4px;
}
