@page { 
    size: 8.27in 11.69in; /* A4 width and height */ 
    }
.hrClass{
	border-top: 1px solid #000000;
}
.pacemakerTable{
	margin-top: 3pt;
}
table.pacemakerTable td{
	vertical-align: top;
	}
.h3Class{
	font-size: 12pt;
	margin-bottom: 0.5pt;
	margin-top: 1pt;
	font-weight: lighter;
	}
.h4Class{
	font-size: 11pt;
	margin-bottom: 1pt;
	margin-top: 3pt;
	}
.pClass{
	margin: 0.5px;	
	}
.border, .border tr, .border td{
	border: 0.5px solid black;
	border-collapse: collapse;
	border-spacing: 0px;
	text-align: center;
	padding: 1.5px;
	min-height: 8pt;
	}
.border th{
	background-color: #D3D3D3;
	text-align: center;
	border-top: 0px solid black;
	}
.topcorner{
	top:0;
	right:0;
	text-align: right;
	padding-right:20pt;
	}
#header{
	margin-bottom:35pt;
	}
.pacerNoteboxs{
	border: 1px solid black;
	width: 405pt;
	height: 40pt;
	float: right;
	margin-top: 2px;
	}