@page { size: 8.27in 11.69in; /* A4 width and height */ }
html { 
	font-size: 6pt; 
	font-family: Arial, Helvetica, sans-serif;
	padding-left:10pt;
	}
.tpid_p 	{
	font-size: 8pt;	
	min-height: 10pt;
	}
.tpid_highlight{
		padding: 0pt;
		padding-top: 2pt;
		margin: 0pt;
		overflow: hidden;
		white-space: nowrap; /* Don't forget this one */
		text-overflow: ellipsis;
		text-transform: uppercase;
	}
.tpid_table { 
	width: 100%;
	
	}
.tpid_td { 
	vertical-align: top;
	max-width: 10%;
	}
.tpid_h3{
	text-align: center;
	color: #587A93;
	margin: 0px;
	padding: 0px;
	}
	
.tpid_headline{
	padding-top: 20pt;
	text-align: center;
	color: #587A93;
	font-size: 9pt;
}
.tpid_rightbottom{
    display: block;
    margin-left: auto;
    margin-right: 0px;
    width: 50%;
	font-size: 7px;
}
.tpid_upsideDownText{
	display: block;
    margin-left: auto;
    margin-right: auto;
    padding-bottom: 20pt;
	}
.tpid_underLogo{
	padding-left: 22pt; 
	padding-top: 7px;
	color: #587A93;
}
	
.tpid_half {
	width: 50%; 
	}
.tpid_bottomborder {
	border-bottom: 1px solid black;
	border-collapse: separate;
	border-spacing: 0px;
	padding-top: 6px;
}
.tpid_nopadding{
	padding: 0pt;
	padding-left: 5pt;
}