@page { 
	margin-right : 0cm;
	margin-left : 0cm;
	line-height: 1.1em;
	}
.pds_html { 
	font-size: 8pt; 
	font-family: Arial Unicode MS;
	margin-top: 20pt;
    margin-right : 1.5cm;
	margin-left : 1.5cm;
	}
.pds_p { font-weight: bold;
	font-family: 'Arial';}
	b{
		font-family: 'Arial';
	}
.pds_table { 
	width: 100%;
	border-collapse: collapse;
	}
.pds_td { 
	vertical-align: top;
	height: 12pt;
	padding: 0px;
	margin: 0px;
	}
br{
	padding: 0px;
	margin: 0px;
}
.pds_half {
	width: 50%; 
	}
.pds_third{
	width: 33%;
	}
.pds_topborder {
	border-top: 1px solid black;
}
.pds_leftborder {
	border-left: 1px solid black;
}
.pds_nopadding{
	padding: 0pt;
	padding-left: 5pt;
}
.pds_clearpadding{
	padding: 0pt;
	margin: 0pt;
	line-height: 1.1em;
}
.pds_topcorner{
	position:absolute;
	top:0;
	right:0;
	text-align: right;
	padding: 2pt;
	}
#pds_header{
	margin-bottom:30pt;
	}