@page {
	margin : 0cm 0cm 0cm 0cm;	
}
.page-break {
    display : block;
    page-break-after:always;
}

.sv_header {
    margin-top : 5px;
	margin-left : 1.5cm;
	font-size : 13px;
    font-family : sans-serif;
}

.sv_container {
	margin-right : 2cm;
	height : 100%;
}

.sv_voucherdiv {
	margin-left : 85%;
	display : block;
}

.sv_headerdiv {
	font-size : 28px;
	font-weight : bold;
}

.sv_horizontalline {
	border-top : 3px solid black;
	height : 0px;
}

.sv_accointinfo_leftdiv {
	width : 50%;
	margin-top : 5px;   
	display : inline-block;
	border-right : 1px solid black;
}

.sv_accointinfo_rightdiv {
	display : inline-block;
	vertical-align : top;
	padding-top : 10px;
	padding-left : 20px;               	
}

div.sv_accointinfo_leftdiv div {
	padding : 1px;
}

.sv_termConDiv {
	margin-top : 1.5cm;
	margin-left : 2cm;
	margin-right : 2cm;
	height : 100%;
    font-size : 11px;
    font-family : sans-serif;
}

.sv_termConDiv_leftdiv {
	max-width : 47%;
	display : inline-block;
	vertical-align : top;
	text-align : justify;
	text-justify : inter-word;
	padding-right : .5cm;
	color : #404040;	
}

.sv_termConDiv_rightdiv {
	display : inline-block;
	vertical-align : top;
	padding-left : .5cm;
	text-align : justify;
	text-justify : inter-word;
	max-width : 46%;
	color : #404040;
}

.sv_footerdiv_left {
	display : inline-block;
	width : 40%;
	margin-top : .8cm;
}

.sv_footerdiv_middle {
	display : inline-block;
	width : 20%;
	bottom : 0;
}

.sv_footerdiv_right {
	display : inline-block;
	float : right;
}

.sv_devicetable {
	width : 100%;
	border-collapse : collapse;
}

table.sv_devicetable td {
	border : .5px solid black;
	min-height : 14px;
}

.sv_checkbox_div {
	width : 10px;
	height : 10px;
	border : 1px solid black;
	display : inline-block;
}